# Site/SEO settings
email: anastasia@melekou.com
baseurl: ""
paginate: 12
paginate_path: "/page/:num"
permalink: /:title/
google_analytics:

name: Achilles Nasios
title: Photo Games
description: >
  This website presents the produce of the internet photo games which happened weekly during last year.
url: https://photogames.tk
twitter_username:
default_img: /assets/images/seo.jpg
contact_img: /assets/images/contact.jpg
social:
  - name: facebook
    url: https://www.facebook.com/achilles.nasios
  - name: instagram
    url: https://www.instagram.com/achilles.nasios/
  - name: github
    url: https://github.com/achillesn

# Disqus settings
disqus:

# MailChimp settings
mailchimp_action: https://photogames.us18.list-manage.com/subscribe/post?u=b93eeb446f58622e32bc10a23&amp;id=1e76e85166
mailchimp_input: b_b93eeb446f58622e32bc10a23_1e76e85166

# Author settings
author:
  - name: Achilles Nasios
    bio: Achilles Nasios is a photographer, video-artist and an art teacher.  He was born in Greece, studied in Prague, Berlin, Athens and Stockholm. Worked as a lecturer of photography at the Greek University. He lives and works in Sweden.
    url: http://anikon.org

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
